### ISSUE TITLE
Feature Request: wrap on infoview boundaries

### ISSUE THREAD

**Issue by Seasawher** [leanprover-community/lean4web#10]
Thank you for a nice web editor!

I would like it to be possible to switch whether the code wraps at the right edge or not, as in VSCode.

**Comment by joneugster** [comment]
Sorry for the long delay. This is now on `main`, which means it will be on [lean.math.hhu.de](https://lean.math.hhu.de/) (our personal test server) tomorrow and on [live.lean-lang.org](https://live.lean-lang.org/) the next time the FRO updates their instance (which happens manually, I think)

**Comment by Seasawher** [comment]
Thank you!!

**Comment by nomeata** [comment]
I just deployed this on https://live.lean-lang.org/. Let me know if I broke anything.

**Comment by nomeata** [comment]
And feel free to ping me on zulip when another update is due
