### ISSUE TITLE
infoview "copy message to comment" looses stuff

### ISSUE THREAD

**Issue by joneugster** [leanprover-community/lean4web#13]
See [Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/https.3A.2F.2Flive.2Elean-lang.2Eorg.2F/near/405820065).

In the following example, the infoview button "copy message to comment" copies an incomplete error message to context.

```
import Mathlib

example : 1 + 1 = 2 := Nat.add_one
```

**Comment by abentkamp** [comment]
We'll need a new release of the `@leanprover/infoview` npm package. I have written to Wojciech about this.
