### ISSUE TITLE
bug: Japanese characters have an incorrect wrapping position.

### ISSUE THREAD

**Issue by Seasawher** [leanprover-community/lean4web#21]
related #10 

Japanese characters have an incorrect wrapping position.

![no_wrap](https://github.com/leanprover-community/lean4web/assets/47292598/95609577-8021-4916-971a-7cce78bf46fa)
![wrap](https://github.com/leanprover-community/lean4web/assets/47292598/ed853fde-093b-4db6-a941-858aa4fc1c5b)

**Comment by joneugster** [comment]
Sorry, I don't understand from the screenshots what's not working.


Also, could you add some code for copy-pasting and reproducing quicker, please?

**Comment by Seasawher** [comment]
Sorry. This is the code.

```lean
def ja := "いろはにほへとちりぬるをわかよたれそつねならむうゐのおくやまけふこえてあさきゆめみしゑひもせす"

def en := "The quick brown fox jumps over the jazy dog"

def polish := "Pchnąć w tę łódź jeża lub ośm skrzyń fig."

def russian := "В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!"

def chinese := "天地玄黄宇宙洪荒日月盈昃辰宿裂張寒来暑往秋収冬蔵閏余成歳律呂調陽"
```

I tested again this time and it seems to depend on the font whether this problem is reproduced or not.

**Comment by Seasawher** [comment]
In other words, if #7 is resolved, this is automatically resolved. This can be considered a duplication of #7.

**Comment by joneugster** [comment]
#7 is fixed, also on the live version!

(you need to turn on word wrapping in the settings. And also select "Save my settings" to keep it across reloads.

**Comment by Seasawher** [comment]
this issue still exists at <https://lean.math.hhu.de/>.

**Comment by Seasawher** [comment]
When narrowing the width, line breaks will be inserted.

![before_wrap](https://github.com/leanprover-community/lean4web/assets/47292598/035cf6fd-09f7-4c76-ba50-e950a2e669c8)

![after_wrap](https://github.com/leanprover-community/lean4web/assets/47292598/8c92e904-6a99-4279-9c89-b79cb0ae4fab)

**Comment by joneugster** [comment]
I don't consider it a bug that it first wraps at the space before breaking any words, i.e. line 1 in your screenshot seems fine. (although, maybe one could set `wrappingStrategy="advanced"`, see [monaco doc](https://microsoft.github.io/monaco-editor/typedoc/interfaces/editor.IEditorConstructionOptions.html#wrappingStrategy))

However, it seems that it wraps japanese & chinese characters wrongly, so that some aren't visible. Right?

**Comment by joneugster** [comment]
Hmm. Looks like these japanese/chinese characters are treated as double-witdh by monaco, but are only displayed about 1.5x monospace width by the font...

```lean
def a := "いろはにほへとちりぬるをわかよたれそつねならむうゐのおくやまけふ"
def b := "天地玄黄宇宙洪荒日月盈昃辰宿裂張寒来暑往秋収冬蔵閏余成歳律呂調陽"
def c := "1122334455667788990011223344556677889900112233445566778899001122"
```

**Comment by joneugster** [comment]
`wrappingStrategy: "advanced"` seems to fix the wrapping of chinese/japanese characters at least :)

**Comment by Seasawher** [comment]
日本語文字の折り返しを https://lean.math.hhu.de/ でテストしてみた。問題は解決したようだ！ありがとう
