### ISSUE TITLE
feature request: import package

### ISSUE THREAD

**Issue by Seasawher** [leanprover-community/lean4web#22]
### Current situation

* Packages other than mathlib cannot be used.
* To add more packages that can be used with lean4 web, changes need to be made to the lean4 web code

### I want a feature such that...

* Import packages in-place on the lean4 web based on GitHub repository URLs.

**Comment by joneugster** [comment]
It is possible for the admin of a server to provide featured packages (for example [here](https://lean.math.hhu.de/#project=DuperDemo&url=https%3A%2F%2Fraw.githubusercontent.com%2FJOSHCLUNE%2FDuperDemo%2Fmain%2FDuperDemo.lean) we provide the "Duper Demo" lean package). And one can switch in the settings between the finite amount of admin-chosen projects.

However, with the current setup ("everything runs server-side"), I don't think it's feasible to allow users to essentially upload to the server and have them built on the server.

However, what would be the advantage over gitpod?
