### ISSUE TITLE
Consider disable context-menu in mobile view

### ISSUE THREAD

**Issue by onriv** [leanprover-community/lean4web#29]
(This is copied from the corresponding [zulip thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/https.3A.2F.2Flive.2Elean-lang.2Eorg.2F/near/446000115)) Hi lean4web is very nice using from a mobile phone too! Using it in mobile env I find it is a little inconvenient for selecting text. Could it be possible with an option bringing the system panel rather than the vscode panel up? Using IOS in most editing environments if I hold touching the screen, the system panel with "paste/select/select all" shown and in llo the vscode command panel shown. Most of the time the vscode command panel works perfectly but not quite for selecting texts:

https://github.com/leanprover-community/lean4web/assets/1629055/a91b9b8d-83ce-47ef-8312-e4993661742a

**Comment by joneugster** [comment]
Done in the updated Version, which is live for testing at lean.math.hhu.de

**Comment by joneugster** [comment]
- [ ] on an empty editor, I cannot make the mobile keyboard appear
- [ ] selecting is still somewhat akward. Selecting one word works, but cannot modify selection.
