### ISSUE TITLE
Recommended infra to run with all mathlib

### ISSUE THREAD

**Issue by desaxce** [leanprover-community/lean4web#40]
Thank you for the project!

You mention running this lean4web on Ubuntu, could you please share the specs of the machine running the live version https://live.lean-lang.org/? 

I've been testing with a few VMs on GCP (n2, 16 GB 2 vCPUs), but I tend to get lag and "busily processing" yellow tooltip whenever I paste a block of code.

**Comment by joneugster** [comment]
I believe live.lean-lang.org is run on nix-os. On lean.math.hhu.de is run on ubuntu where we have 50GB RAM and 16 CPUs, although you probably don't need these specs.

Although, I believe the initial loading in Lean (yellow progress bar, not specific to the web editor) is parallelised and would heavily profit from more CPUs. That could be something to ask in Zulip "lean4" channel about for more details.

There should also be an option to the `lean`/`lake` commands which limit the max. number of CPUs used, which would help with the lag. (also not webeditor specific, but these could be modified in the code here or added as a config option.)

**Comment by desaxce** [comment]
Excellent, thanks so much for the answer, I'll try increasing CPU settings!

**Comment by desaxce** [comment]
I increased the number of vCPUs to 6, but what really made a difference was the `lake serve -- -j 4`. 

The "busily processing" warning now disappears in 3 seconds. Still slower than my machine in local, but much much better. 

On a side note, the issue was particularly present for snippets where I did a full `import Mathlib`. 

Thanks again!
