### ISSUE TITLE
Feature Request: use different font

### ISSUE THREAD

**Issue by Seasawher** [leanprover-community/lean4web#7]
I am always grateful to lean4web. Thanks.

It would look even more beautiful if fonts like JuliaMono could be used.
https://juliamono.netlify.app/

**Comment by Seasawher** [comment]
All I had to do was change the browser font myself... Sorry, I didn't realise that.

**Comment by Seasawher** [comment]
Not everyone can conceive of installing a font and changing the settings in their browser. Wouldn't it be nice to choose a font that displays Unicode readably by default?

**Comment by joneugster** [comment]
It would be very reasonable to have a reasonable default font!

(not google though, I believe there is something about google fonts not bein GDPR conform or some nonesense like that)

**Comment by Seasawher** [comment]
My mother tongue is Japanese and I usually use the font Juisee for Lean.

See https://github.com/yuru7/juisee

It would be preferable if this could be made convenient for non-English speakers.

**Comment by joneugster** [comment]
I'd happily accept a PR that adds the correct fonts.

Currently Mac-users also have a hard time because for most of them it does not load a mono-space font.

**Comment by joneugster** [comment]
On my end it looks very reasonable, doesn't it?

CSS says: `font-family: "Droid Sans Mono", "monospace", monospace`

Do you think it would be satisfactory to just ship "droid sans mono" together with the bundle?

![Screenshot_20240423_092520](https://github.com/leanprover-community/lean4web/assets/9141564/5e3846cf-9bd5-455e-8c74-f4b869553f8d)

**Comment by Seasawher** [comment]
Sorry, I don't know how to install Droid Sans Mono and can't try it myself.

Looks good, but do the Unicode symbols used in mathematics show up clearly?

**Comment by joneugster** [comment]
I realised that 'Droid Sans Mono' was just a random font on my computer. I did change the editor to use `JuliaMono` now.

Could you test at https://lean.math.hhu.de/ and see if it all looks good @Seasawher ?

**Comment by Seasawher** [comment]
I found a problem:

When you try to define `longlonglong....name`, there was a problem with the cursor "lagging" behind the displayed character.

![longname_font](https://github.com/leanprover-community/lean4web/assets/47292598/c10eb0a6-5e06-4f1e-bae6-6a110ebd3bc0)

see <https://lean.math.hhu.de/#code=def%20longlonglonglonglonglonglonglonglongname%20%3A%3D%22hoge%22%0D%0A%0D%0A>

**Comment by Seasawher** [comment]
I found another problem ... I think this is a bug in Julia Mono rather than in Lean4 Web, but the kanji character for "点" (which means "dot") is displayed incorrectly.

![image](https://github.com/leanprover-community/lean4web/assets/47292598/2be0a576-7c93-492f-930d-c3523f94f238)

**Comment by joneugster** [comment]
> In the image above, the cursor is shown as being in the middle of the line, but it actually exists at the end of the line.

I cannot reproduce this on my end. Could it be some local (CSS) caching? If it persists, please open a new issue about it!

Regarding "点" , reading the linked issue, I think we just need to update the font in a few weeks.

**Comment by Seasawher** [comment]
It might be a good idea to have others test it

**Comment by Seasawher** [comment]
I think this issue itself has been resolved.
